### ISSUE TITLE
add ability to select existing images

### ISSUE THREAD

**Issue by jamemackson** [hairbrain/gallery13#20]
this is needed for allowing the user to select existing images already uploaded to the server.

We'll want to expand on the image-upload-button component @ianVS created.

We may want to wrap the image-upload-button in a image-selector component where the user can either select an existing asset or upload a new asset and both will keep the image.path bound to the user selection.

**Comment by IanVS** [comment]
I think this should likely be a separate component from the image-upload-button, since in this case we won't be uploading anything to the server, just setting some properties.  Maybe it would even be possible to use something like https://github.com/thefrontside/emberx-select

**Comment by jamemackson** [comment]
Yes I think using something like that for selecting the existing image is great.  When I wrote this up I was thinking more about allowing the user to select from a list of images uploaded to the server already vs selecting from existing image records in the database.  But I guess if we play our cards right in how we code this there shouldn't be any difference between those files and the image records... 

I do think we should then wrap whatever we use to select an existing image record and the image uploader into a single component that can be used to edit images...

**Comment by IanVS** [comment]
> I do think we should then wrap whatever we use to select an existing image record and the image uploader into a single component that can be used to edit images...

Maybe you can explain this a little more?  Those seem like separate functionalities, and I'm not seeing what the benefit would be to bundling them in a single component.

**Comment by jamemackson** [comment]
Just ease of reuse I guess.  But now I'm wondering if it was more of a muddled thought.  We have a number of places where we reference images like the artist.featureImage property but now I'm thinking we should just use a component that would allow them to select an existing image record instead.  In any case I think we should just keep this really simple and get it out the door haha :)

**Comment by IanVS** [comment]
Added [ember-cli-selectize](https://github.com/miguelcobain/ember-cli-selectize) in https://github.com/hairbrain/gallery13/commit/884698c5eab996631efe47dc50f92ec0186ee7be
