### ISSUE TITLE
create user editing functionality in admin

### ISSUE THREAD

**Issue by jamemackson** [hairbrain/gallery13#24]
for now we will allow any admin user (any user at all really) to administer users for the site.

We'll want general crud editing functionality and hide or mask passwords for users but do allow updating passwords.

**Comment by IanVS** [comment]
Are there other types of users for this site other than admins and anonymous?

**Comment by jamemackson** [comment]
For now we'll assume everyone logged in is an admin.  Eventually he would like artists and others to be able to login with access to different functionality but let's keep it simple for the urial launch.

**Comment by jamemackson** [comment]
**initial
