### ISSUE TITLE
Upload files directly to S3

### ISSUE THREAD

**Issue by jamemackson** [hairbrain/gallery13#34]
As we discussed, we should update the uploader to push files directly to S3

Here's what I can see as steps to accomplish this 
- [ ] setup S3 bucket
  - [x] create "gallery13" bucket
  - [x] create "gallery13-dev" bucket
  - [x] create dev and prod folders to hold files for respective environments
  - [x] create a IAM user "gallery-server"
  - [ ]  setup Bucket permissions
- [x] update [UploadController](https://github.com/hairbrain/gallery13/blob/master/server/api/controllers/UploadController.js#L22-L26) to point to S3

**Comment by jamemackson** [comment]
for the code I just checked in to work, we need to add a config file here:
```js
//   /server/config/local.js
module.exports = {
    uploadS3: {
      key: 'API-KEY-HERE', // API key
      secret: 'API-SECRET-HERE', // API secret
      bucket: 'BUCKET-NAME-HERE'  // Name of bucket to upload to
    }
}
```
@IanVS this reminds me we should figure out a good way to pass credentials back and forth ;) 

I'll get you the details for what I setup in S3 for this...

**Comment by IanVS** [comment]
Hopefully we can use an environment variable in the CI server to store this. I don't like having secrets in config files.

**Comment by jamemackson** [comment]
yea I totally agree there.  And I believe we should be able to use environment variables.  I just wanted to get this working which is why I used the `server/config/local.js` file for now which isn't checked in...  Figuring that we can migrate those secrets into the right spot afterwords.

**Comment by jamemackson** [comment]
I have this working but we still need to look more into proper S3 permissions as I feel like I have things overly open in S3 to get this working initially.

S3 connection info and what bucket to use is configured using environment variables and/or a `.env` file in the `/server/` folder.  This file should look like the following

```
S3_KEY=YOUR-KEY-HERE
S3_SECRET=YOUR-SECRET-HERE
S3_BUCKET=gallery13
```
