### ISSUE TITLE
update gallery.hairbrain.io with latest master

### ISSUE THREAD

**Issue by jamemackson** [hairbrain/gallery13#39]
I started to update the site on the server.  I ran into a few issues - think I messed something up on your otherwise nicely running node server @IanVS :) maybe some of these you experienced already?

I started reading thru some of your documentation to see if I can learn the error in my ways but realize I need to spend a bit more time to take it all in so the http://gallery.hairbrain.io site is down at the moment.  

 - I ran into some out of memory errors when running `npm install` in client and server folder

this seemed to be better once I stopped PM2 but was still error prone so I compiled the client locally and manually copied the files over

 - 502 Bad Gateway error loading client

once I got the ember files pushed up to  'server/assets` but I'm not getting an nginx error.  It's getting late so I thought I'd log what was going on and see if you, @ianvs, had any ideas off the top of your head.  After logging into it I think this is the server that I think you built and not that original one I had built.  I haven't really done much with nginx so I wasn't sure beyond the obvious of restarting it which didn't change the error message.  

The current error message.  
```
502 Bad Gateway
nginx/1.8.0
```

 - then realized there were other errors starting the site directly with node 

and that's where the train really fell off the rails.  when I run `node app.js --prod` in the server directory it gives me the following:

```
ubuntu@ip-172-31-30-164:~/gallery13/server$ node app.js --prod
module.js:338
    throw err;
    ^
Error: Cannot find module 'bcrypt'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/ubuntu/gallery13/server/api/models/User.js:1:76)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /home/ubuntu/gallery13/server/node_modules/include-all/index.js:129:29
    at Array.forEach (native)
    at requireAll (/home/ubuntu/gallery13/server/node_modules/include-all/index.js:44:9)
    at buildDictionary (/home/ubuntu/gallery13/server/node_modules/sails/node_modules/sails-build-dictionary/index.js:68:14)
    at Function.module.exports.optional (/home/ubuntu/gallery13/server/node_modules/sails/node_modules/sails-build-dictionary/index.js:160:9)
```

which I kind of think may be related to the `npm install` error above?  after killing PM2, the npm install seemed to finish but maybe it was really still having some problems I didn't catch?

Anyways, there's as far as I got tonight.  Off to bed for me.

**Comment by IanVS** [comment]
After stopping pm2, I tried an `npm install` in the server, and found that bcrypt was failing due to not having g++ installed on the box.  A `sudo apt-get update` and `sudo apt-get install g++` took care of that, and subsequently `npm install` succeeded.

The second issue was that sails was trying to start on port 80, which isn't allowed by non-sudo processes.  The nginx reverse proxy can be configured to send traffic to a higher port, which I will set up shortly.

I also need to configure ember to reference the correct api server in production.  I'm testing everything out now and will commit changes.

**Comment by IanVS** [comment]
Another thing: mysql seems to not be set up properly, meaning the user and password and such.  I would prefer to leave that to you, since you've done the mysql work so far.

**Comment by jamemackson** [comment]
the site is back online again!  :) closing this task for now.  Feel free to reopen if you feel like more work is warranted against it.
