### ISSUE TITLE
add ability to add new artist images via /artist/:artist_slug/edit/new-image

### ISSUE THREAD

**Issue by jamemackson** [hairbrain/gallery13#4]

**Comment by IanVS** [comment]
Do you have something in mind here?  If you'd like, I can add an uploader similar to what I did in how-to-sane, using [ember-cli-plupload](https://github.com/paddle8/ember-plupload)

**Comment by jamemackson** [comment]
yes, I think setting that up would be great.  I need to do some clean up of some of the modeling where we're relating 1 or many images in various places.  I'll see about cleaning that up this evening.  

I think for now we definitely need to add the ability to upload images for artist, the `artist.images` property.  Maybe we start there, establish a pattern, and then replicate that as we need for the rest of the places we need to manage images.

I also think we should setup some kind of default structure for how we store the images on the server as well.  for the artist images, maybe something like 
`/images/{artist.slug}/{artist.image.name}`

**Comment by IanVS** [comment]
I've set up the initial functionality for adding new images in e76f79df5cb68a7e04c98471662f226728ccd7a4, fa0d46e0624024548b698339c91e09fbdacbe22f, and fc3fbddf4bec17bc83fc5fdbdcc1eff2b9cbbf2b.

The preview image needs some styling to keep it small, and there are probably other style tweaks that can be made, but the base functions should work.

**Comment by jamemackson** [comment]
I really like what you have going here.  The image upload parts work just fine for me when I tried it.  I'd like to do a few more things before we call this one good.  

- [ ] display the uploaded file path set in `image.path`
- [ ] limit size of preview image
- [ ] fix saving of image record
- [ ] add the ability to select an image already uploaded (I created #20 for this)
- [ ] fix loading of edit image url null reference - example: `http://localhost:4200/admin/artist/2/edit-image/null`

I'm guessing I should really just create separate issues for [ some or all ] of this and really need to do a more complete analysis of what we have left to do to get the site ready for an initial release....

**Comment by IanVS** [comment]
Looks like we can also upload images straight to S3 using (https://github.com/paddle8/ember-plupload#s3-direct-uploads)  I think that is a better approach than putting the images in server/assets, do you agree?  That way images be served from a CDN, and removed from the git repository which should improve deployment speed and save EBS disk space. What do you think?

**Comment by jamemackson** [comment]
I like the idea of having image and other static uploads go right to S3.  I imagine the storage cost will be cheaper in the long run as well.  :)

**Comment by IanVS** [comment]
> display the uploaded file path set in image.path

Where do you want this path to be displayed?  I'm thinking maybe a title tag on the image preview?  See commit 26b2d71.  I tried adding it below the description first, but the URLs get too long and throw everything off.  But that's just because I'm lazy and not very good with styling.

**Comment by jamemackson** [comment]
I was thinking of displaying this on the admin side when editing an image is all.

**Comment by IanVS** [comment]
OK, yeah, I haven't done anything with editing yet.  Will get on that next.

**Comment by jamemackson** [comment]
Awesome :)

**Comment by IanVS** [comment]
> fix loading of edit image url null reference

Is this still an issue?  Not sure what the issue is.

**Comment by jamemackson** [comment]
I think we can call this one good as it stands.  I'm going to create a new issue for updating the uploader to go right to S3
